App_Two/urls.py
from django.conf import urls
from . import views
from django.urls import path


app_name='my_app'
urlpatterns=[
    path('first',views.first,name='first'),
    path('second',views.second,name='second'),
    path('user',views.users,name='user'),
    path('register',views.register,name="register")

]

project_two/urls.py
from django.contrib import admin
from django.urls import path,include
from App_Two import views




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.first_app,name='first_app'),
    path('',include('App_Two.urls'))
]

App_Two/models.py
from django.db import models

class Topic(models.Model):
    top_name=models.CharField(max_length=100,unique=True)
    date1=models.DateTimeField()
    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic=models.ForeignKey(Topic,models.CASCADE)
    name=models.CharField(max_length=100,unique=True)   
    url=models.URLField(unique=True) 

    def __str__(self):
        return self.name
class AccessRecord(models.Model):
    name=models.ForeignKey(Webpage,models.CASCADE)
    date=models.DateField()

    def __str__(self):
        return str(self.name)  
    

class user(models.Model):
    First_name=models.CharField(max_length=100)
    Last_name=models.CharField(max_length=120)
    email_id=models.EmailField()   

    def __str__(self):
        return self.First_name 
    

App_Two/forms.py
from django import forms
from App_Two.models import user

class myform(forms.ModelForm):
    class Meta():
        model=user
        fields='__all__'

App_Two/views.py
from django.shortcuts import render
from django.http import HttpResponse
from App_Two.forms import myform
from App_Two.templatetags.filers import cut
from .models import Topic,Webpage,AccessRecord,user


# Create your views here.
def first_app(request):
    my_dict={'text':'hello all how are you','number':'200'}
    text_value = my_dict['text']
    filtered_text = cut(text_value, 'h')
    print(f"Original text: {text_value}")
    print(f"Filtered text: {filtered_text}")
    return render(request,'base.html',my_dict)

def first(request):
    my_text={'insert':"Hello All Im from views....!!!"}
    return render(request,'index.html',context=my_text)
def second(request):
    items_list=Topic.objects.order_by('date1')
    date_dict= {'access_items':items_list} 
   # my_text2={'insert':"Hello All Im from views....!!!"}
    return render(request,'second.html',context=date_dict)

def users(request):
    users_list=user.objects.order_by('Last_name')
    user_dict={'access_users':users_list}
    return  render(request,'user.html',context=user_dict)

def register(request):

    form=myform()
     
    if request.method =="POST":
        form= myform(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return first_app(request)
        else:
            print("Form Invalid")
     
     
    return render(request,'register.html',{'form':form})

templates/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-light navbar-light">

        <div class="container-fluid">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="navbar-brand" href="#">Brand</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'my_app:register' %}">Registerpage</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Adminpage</a></li>
            </ul>
           
        </div>
    </nav>
    <h1>{{ text|upper }} {{ number|add:30}}</h1>
    <h1>{{ text|cut:'l'}}</h1>
    


    <div class="container">
        {% block content %}


        {% endblock %}
    </div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/mycss.css' %}">
    <title>Document</title>
</head>
<body>
    <h1>HellO This is picture of Squirrel</h1>
    {{insert}}
    <img src="{% static 'images/squirrel.jpeg' %}" alt="animal">
    <img src="{% static 'images/animal.jpg' %}" alt="animal_two" style="height:200px;width:100px"><br>
    <a href="{% url 'my_app:second'  %}">second.html_page</a>
    <a href="{% url 'admin:index'  %}">admin_page</a>
</body>
</html>

templates/register.html
{% extends 'base.html' %}

    {% block content%}
    <h1>This is form registration page</h1>

    <div class="container">
        <form method="POST">
        {{ form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-success" value="submit">
    
</form>
</div>

{% endblock content %}

templates/second.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%  static 'css/second.css' %}">
    <title>Document</title>
</head>
<body>
    <h1>This is for sorting the items</h1>

    {% if access_items %}
    <table border="5">
        <thead>
            <th>Item_name</th>
            <th>Date&time</th>
        </thead>
    
     {% for item in access_items %}
     <tr>
        <td>{{item.top_name}}</td>
        <td>{{item.date1}}</td>
     </tr>
   
     {% endfor %}
    </table>
     {% endif %}
</body>
</html>

templates/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>This is my users page</h1>

    {% if access_users %}

    <ol>

        {% for person in access_users %}
        <li>user Info</li>
        <ul>
            <li>First Name: {{person.First_name}}</li>
            <li>Last Name: {{person.Last_name}}</li>
            <li>Email: {{person.email_id}}</li>
        </ul>
        {% endfor %}
    </ol>

    {% endif %}

</body>
</html>